// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

User _$UserFromJson(Map<String, dynamic> json) => User(
      (json['id'] as num?)?.toInt(),
      json['code'] as String?,
      json['member_type'] as String?,
      json['fname'] as String?,
      json['lname'] as String?,
      json['phone'] as String?,
      json['birth_date'] as String?,
      json['gender'] as String?,
      json['importer_code'] as String?,
      json['password'] as String?,
      json['referrer'] as String?,
      json['address'] as String?,
      json['province'] as String?,
      json['district'] as String?,
      json['sub_district'] as String?,
      json['postal_code'] as String?,
      json['wallet_balance'] as String?,
      json['point_balance'] as String?,
      json['image'] as String?,
      json['avaliable_time'] as String?,
      json['credit_limit'] as String?,
      json['loan_amount'] as String?,
      json['bus_route'] as String?,
      json['email'] as String?,
      json['facebook'] as String?,
      json['line_id'] as String?,
      json['wechat'] as String?,
      (json['notify_sms'] as num?)?.toInt(),
      (json['notify_line'] as num?)?.toInt(),
      (json['notify_email'] as num?)?.toInt(),
      json['found_via'] as String?,
      (json['priority_update_tracking'] as num?)?.toInt(),
      (json['priority_package_protection'] as num?)?.toInt(),
      (json['priority_order_system'] as num?)?.toInt(),
      json['responsible_person'] as String?,
      json['responsible_sale'] as String?,
      json['responsible_remark'] as String?,
      json['id_card_copy'] as String?,
      json['company_certificate'] as String?,
      json['pp20_document'] as String?,
      json['language'] as String?,
      json['member_address'] == null
          ? null
          : MemberAddress.fromJson(
              json['member_address'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'id': instance.id,
      'code': instance.code,
      'member_type': instance.member_type,
      'fname': instance.fname,
      'lname': instance.lname,
      'phone': instance.phone,
      'birth_date': instance.birth_date,
      'gender': instance.gender,
      'importer_code': instance.importer_code,
      'password': instance.password,
      'referrer': instance.referrer,
      'address': instance.address,
      'province': instance.province,
      'district': instance.district,
      'sub_district': instance.sub_district,
      'postal_code': instance.postal_code,
      'wallet_balance': instance.wallet_balance,
      'point_balance': instance.point_balance,
      'image': instance.image,
      'avaliable_time': instance.avaliable_time,
      'credit_limit': instance.credit_limit,
      'loan_amount': instance.loan_amount,
      'bus_route': instance.bus_route,
      'email': instance.email,
      'facebook': instance.facebook,
      'line_id': instance.line_id,
      'wechat': instance.wechat,
      'notify_sms': instance.notify_sms,
      'notify_line': instance.notify_line,
      'notify_email': instance.notify_email,
      'found_via': instance.found_via,
      'priority_update_tracking': instance.priority_update_tracking,
      'priority_package_protection': instance.priority_package_protection,
      'priority_order_system': instance.priority_order_system,
      'responsible_person': instance.responsible_person,
      'responsible_sale': instance.responsible_sale,
      'responsible_remark': instance.responsible_remark,
      'id_card_copy': instance.id_card_copy,
      'company_certificate': instance.company_certificate,
      'pp20_document': instance.pp20_document,
      'language': instance.language,
      'member_address': instance.member_address,
    };
